### ISSUE TITLE
'forceExit: true' prevents further grunt tasks from running

### ISSUE THREAD

**Issue by digitor** [jribble/grunt-jasmine-node-coverage#38]
I assume 'forceExit: true' is meant to stop the script only if there is an exception. However, even when I get no errors and my grunt tasks seem to be running correctly, no further tasks are running after my 'jasmine_node' target. 
I'm just trying to run 'grunt-contrib-clean' after it. Sounds like an async 'done()' not getting called somewhere. 
If I leave 'forceExit' as false, it runs as expected.

**Comment by jimdoyle82** [comment]
OS: Maveriks (10.9.5)
Node: 0.10.31
Grunt: 0.4.5

**Comment by paazmaya** [comment]
Thank you for pointing that out. The process exists due to the call `process.exit()` in here https://github.com/jribble/grunt-jasmine-node-coverage/blob/master/tasks/jasmine-node-task.js#L296

Perhaps it might make sense to change it to `grunt.warn.error()` or something similar, but not really sure which would serve the users best.

**Comment by jimdoyle82** [comment]
Shouldn't it only force exit if there is a fail of some kind - 'exitCode = 1'?

**Comment by paazmaya** [comment]
That is correct.

Would you like to make a PR for this?

**Comment by jimdoyle82** [comment]
I'll take a look at it this weekend.

**Comment by paazmaya** [comment]
Great!

**Comment by Andre-Gl** [comment]
Guys, any updates on this issue?

**Comment by digitor** [comment]
Yep, just did a pull request. Sorry for taking so long.

**Comment by paazmaya** [comment]
Fix merged in dbec1106b0f1a1f5b7dc074a28b5a6e7bf189ec1

**Comment by Andre-Gl** [comment]
Working now. Thanks a lot!
